"""
simulator/agent.py

MarketMakerAgent for the Avellaneda-Stoikov (2008) market-making framework.

The agent is the central coordinating object for one simulation run.
It owns:
  - An InventoryManager  (tracks q_t, X_t, risk, limits)
  - A ReservationPrice   (computes r(s,q,t) = s - q*gamma*sigma^2*(T-t))
  - A SpreadModel        (computes optimal half-spread delta^a + delta^b)

At every time step the engine calls quote() to obtain fresh bid/ask prices,
then calls on_buy_fill() or on_sell_fill() when a market order hits/lifts
the agent's limit orders.

Paper references (Avellaneda & Stoikov, Quantitative Finance 2008):
  - Reservation price  : eq. (8)   r = s - q*gamma*sigma^2*(T-t)
  - Optimal spread     : eq. (30)  delta^a + delta^b = gamma*sigma^2*(T-t)
                                   + (2/gamma)*ln(1 + gamma/k)
  - Bid quote          : p^b = r - half_spread
  - Ask quote          : p^a = r + half_spread
  - Cash dynamics      : dX_t = p^a dN^a_t - p^b dN^b_t
  - Inventory dynamics : q_t  = N^b_t - N^a_t
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Optional, List

# ---------------------------------------------------------------------------
# Strategy imports  (adjust relative paths to match your package layout)
# ---------------------------------------------------------------------------
from strategy.inventory import InventoryManager, InventoryLimits, InventorySnapshot
from strategy.reservation import ReservationPrice          # r(s,q,t)  [finite horizon]
from strategy.spread import SpreadModel                    # delta^a + delta^b [finite horizon]
from strategy.reservation_infinite import InfiniteHorizonReservationPrice  # [infinite horizon]
from strategy.spread_infinite import InfiniteHorizonSpreadModel            # [infinite horizon]

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data containers
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Quote:
    """
    A pair of bid/ask limit order prices generated by the agent at time t.

    Attributes
    ----------
    bid : float
        Price at which the agent is willing to *buy* one share  (p^b).
    ask : float
        Price at which the agent is willing to *sell* one share (p^a).
    reservation : float
        Underlying reservation (indifference) price r(s,q,t).
    half_spread : float
        Half of the total optimal spread  (delta^a = delta^b = half_spread).
    mid_price : float
        Market mid-price s_t used to compute this quote.
    time : float
        Simulation time t at which this quote was generated.
    """
    bid: float
    ask: float
    reservation: float
    half_spread: float
    mid_price: float
    time: float

    @property
    def spread(self) -> float:
        """Total bid-ask spread (ask - bid)."""
        return self.ask - self.bid

    @property
    def bid_distance(self) -> float:
        """Distance of bid from mid-price (delta^b = s - p^b)."""
        return self.mid_price - self.bid

    @property
    def ask_distance(self) -> float:
        """Distance of ask from mid-price (delta^a = p^a - s)."""
        return self.ask - self.mid_price

    def __repr__(self) -> str:
        return (
            f"Quote(bid={self.bid:.4f}, ask={self.ask:.4f}, "
            f"spread={self.spread:.4f}, r={self.reservation:.4f}, t={self.time:.4f})"
        )


@dataclass
class FillRecord:
    """Record of a single order fill received by the agent."""
    time: float
    side: str           # 'BUY' or 'SELL'
    price: float
    quantity: int       # always 1 in the base model
    cash_delta: float
    inventory_after: int


@dataclass
class AgentState:
    """
    Full observable state of the agent at a given instant.
    Returned by MarketMakerAgent.state().
    """
    time: float
    mid_price: float
    quantity: int
    cash: float
    mark_to_market: float
    reservation_price: float
    risk_exposure: float
    last_quote: Optional[Quote]
    limit_breached: bool
    total_fills: int
    buy_fills: int
    sell_fills: int
    skew_direction: str


# ---------------------------------------------------------------------------
# MarketMakerAgent
# ---------------------------------------------------------------------------

class MarketMakerAgent:
    """
    Coordinates the three strategy modules to produce live bid/ask quotes
    and process order fills during a simulation.

    Parameters
    ----------
    gamma : float
        Absolute risk-aversion coefficient γ.  Controls how aggressively
        the agent skews quotes away from the mid-price to manage inventory.
    sigma : float
        Volatility of the mid-price Brownian motion (σ).
    T : float
        Terminal time of the trading session.
    k : float
        Order-arrival decay parameter.  Higher k → orders arrive only when
        quotes are very close to the mid-price (tighter market).
    A : float
        Baseline order-arrival intensity Λ (market order frequency).
    limits : InventoryLimits, optional
        Hard/soft position limits.  Defaults to InventoryLimits(max_long=10,
        max_short=-10).
    initial_quantity : int, optional
        Starting share inventory q_0 (default 0).
    initial_cash : float, optional
        Starting cash X_0 in dollars (default 0.0).
    quote_side : str, optional
        'TWO_SIDED' (default) — always post both bid and ask.
        'BID_ONLY'  — post only the bid side.
        'ASK_ONLY'  — post only the ask side.

    Attributes
    ----------
    inventory : InventoryManager
    reservation : ReservationPrice
    spread_model : SpreadModel
    quote_history : list[Quote]
    fill_history : list[FillRecord]
    """

    # Sentinels for suppressed sides
    _SUPPRESSED = float("nan")

    def __init__(
        self,
        gamma: float,
        sigma: float,
        T: float,
        k: float,
        A: float,
        model: str = "finite_horizon",
        omega: Optional[float] = None,
        q_max: Optional[int] = None,
        limits: Optional[InventoryLimits] = None,
        initial_quantity: int = 0,
        initial_cash: float = 0.0,
        quote_side: str = "TWO_SIDED",
    ) -> None:
        # ---- validate -------------------------------------------------------
        for name, val in [("gamma", gamma), ("sigma", sigma), ("T", T),
                          ("k", k), ("A", A)]:
            if val <= 0:
                raise ValueError(f"{name} must be strictly positive, got {val}.")
        if quote_side not in {"TWO_SIDED", "BID_ONLY", "ASK_ONLY"}:
            raise ValueError(
                f"quote_side must be 'TWO_SIDED', 'BID_ONLY', or 'ASK_ONLY'."
            )
        if model not in {"finite_horizon", "infinite_horizon"}:
            raise ValueError(
                f"model must be 'finite_horizon' or 'infinite_horizon', got {model!r}."
            )

        # ---- model parameters -----------------------------------------------
        # NOTE: T remains required and strictly positive for BOTH models. For
        # 'infinite_horizon' it is used only as the *simulation duration*
        # (bounds the t-range accepted by quote(), mirrors how the engine uses
        # T to compute n_steps) -- it never enters the infinite-horizon pricing
        # formulas below, which depend on 'omega' instead. This keeps the
        # existing time-bookkeeping/validation untouched for both models.
        self.gamma = gamma
        self.sigma = sigma
        self.T = T
        self.k = k
        self.A = A
        self.quote_side = quote_side
        self.model = model

        # ---- effective inventory limits --------------------------------------
        # Only the infinite-horizon model derives limits from q_max (needed to
        # calibrate omega below); finite-horizon behaviour is fully unchanged.
        if limits is not None:
            effective_limits = limits
        elif model == "infinite_horizon" and q_max is not None:
            # The paper's suggested calibration omega=0.5*gamma^2*sigma^2*(q_max+1)^2
            # keeps the domain 2*omega - gamma^2*sigma^2*q^2 > 0 valid for |q| < q_max,
            # but NOT at q == q_max itself (verified numerically: the reservation-bid
            # log argument hits <= 0 exactly at that boundary -- see
            # strategy/reservation_infinite.py). This codebase's hard inventory limit
            # is inclusive (InventoryManager only suppresses further quoting once
            # q == max_long, i.e. q_max IS a state the simulator can reach), so the
            # DEFAULT limit derived here is set one below the caller's q_max to stay
            # inside the valid domain by construction. This does not alter any
            # simulated inventory value and does not affect callers who pass an
            # explicit 'limits' -- those go through the eager validation below
            # unchanged and raise a clear error if invalid.
            effective_limits = InventoryLimits(
                max_long=q_max - 1, max_short=-(q_max - 1)
            )
        else:
            effective_limits = InventoryLimits()

        # ---- strategy modules -----------------------------------------------
        if model == "finite_horizon":
            self.omega = None
            self.reservation = ReservationPrice(gamma=gamma, sigma=sigma, T=T)
            self.spread_model = SpreadModel(
                gamma=gamma,
                sigma=sigma,
                T=T,
                k=k
            )
        else:  # model == "infinite_horizon"
            if omega is None:
                if q_max is None:
                    raise ValueError(
                        "model='infinite_horizon' requires either 'omega' or "
                        "'q_max' to be provided (q_max is used to derive omega "
                        "via the paper's suggested calibration "
                        "omega = 0.5*gamma^2*sigma^2*(q_max+1)^2)."
                    )
                omega = InfiniteHorizonReservationPrice.omega_for_q_max(
                    gamma=gamma, sigma=sigma, q_max=q_max
                )
            self.omega = omega
            self.reservation = InfiniteHorizonReservationPrice(
                gamma=gamma, sigma=sigma, omega=omega
            )
            self.spread_model = InfiniteHorizonSpreadModel(
                gamma=gamma, sigma=sigma, omega=omega
            )
            # Eager domain validation (per instruction: fail loudly at
            # construction time rather than crashing mid-simulation, and
            # never silently clip). Checks the boundary and centre of the
            # configured inventory range against this omega.
            try:
                for q_check in (0, effective_limits.max_short, effective_limits.max_long):
                    self.reservation.compute(S=1.0, q=q_check, t=0.0)
            except ValueError as exc:
                raise ValueError(
                    f"omega={omega} is not valid across the configured inventory "
                    f"range [{effective_limits.max_short}, {effective_limits.max_long}]: "
                    f"{exc}\n"
                    "Hint: the paper's suggested calibration "
                    "omega=0.5*gamma^2*sigma^2*(q_max+1)^2 keeps the shared "
                    "denominator positive up to |q|=q_max, but the reservation-"
                    "bid log argument can become invalid exactly AT q=q_max. If "
                    "you hit this, either pass a hard inventory limit of "
                    "q_max - 1, or supply a larger 'omega' directly with extra "
                    "margin."
                ) from exc

        self.inventory = InventoryManager(
            gamma=gamma,
            sigma=sigma,
            T=T,
            limits=effective_limits,
            initial_quantity=initial_quantity,
            initial_cash=initial_cash,
        )

        # ---- runtime state --------------------------------------------------
        self.quote_history: List[Quote] = []
        self.fill_history: List[FillRecord] = []
        self._last_quote: Optional[Quote] = None
        self._buy_fills: int = 0
        self._sell_fills: int = 0

    # ------------------------------------------------------------------
    # Primary interface — called by the simulation engine each tick
    # ------------------------------------------------------------------

    def quote(self, mid_price: float, current_time: float) -> Quote:
        """
        Generate optimal bid and ask limit-order prices for the current
        market state.

        Two-step procedure (paper sections 3.1 – 3.2):

        1. Compute the reservation price:
               r = s - q * gamma * sigma^2 * (T - t)            [eq. 8]

        2. Compute the optimal total spread and halve it:
               spread = gamma*sigma^2*(T-t) + (2/gamma)*ln(1+gamma/k) [eq. 30]
               half   = spread / 2

        3. Place quotes symmetrically around the reservation price:
               p^b = r - half
               p^a = r + half

        If a hard inventory limit has been breached on one side, that side's
        quote is suppressed (set to NaN) to avoid worsening the position.

        Parameters
        ----------
        mid_price : float
            Current market mid-price s_t.
        current_time : float
            Current simulation time t ∈ [0, T].

        Returns
        -------
        Quote
            Named tuple carrying bid, ask, reservation, half_spread, mid, t.
        """
        if not (0.0 <= current_time <= self.T):
            raise ValueError(
                f"current_time {current_time} is outside [0, {self.T}]."
            )

        q = self.inventory.quantity
        lim = self.inventory.limits

        # --- Step 1: reservation price ---------------------------------------
        r_result = self.reservation.compute(
            S=mid_price,
            q=q,
            t=current_time,
        )

        r = r_result.price

        # --- Step 2: optimal spread ------------------------------------------
        # q and S are passed in addition to t so that the infinite-horizon
        # spread model (which is inventory-dependent, unlike the finite-
        # horizon Eq. 30 spread) has what it needs. SpreadModel.compute()
        # (finite horizon) accepts and ignores these extra kwargs, so this
        # is a no-op change for model='finite_horizon'.
        spread_result = self.spread_model.compute(
            t=current_time,
            q=q,
            S=mid_price,
        )

        total_spread = spread_result.spread
        half = spread_result.half_spread
        #half = total_spread / 2.0

        # --- Step 3: raw bid / ask -------------------------------------------
        raw_bid = r - half
        raw_ask = r + half

        # --- Hard-limit quote suppression ------------------------------------
        # If already at max long, suppress the bid (no more buying).
        # If already at max short, suppress the ask (no more selling).
        bid = raw_bid if (q < lim.max_long  and self.quote_side != "ASK_ONLY")  else self._SUPPRESSED
        ask = raw_ask if (q > lim.max_short and self.quote_side != "BID_ONLY")  else self._SUPPRESSED

        # Ensure non-negative prices (safety floor)
        if bid == bid:  # not NaN
            bid = max(bid, 1e-6)
        if ask == ask:  # not NaN
            ask = max(ask, bid + 1e-6 if bid == bid else 1e-6)

        q_obj = Quote(
            bid=bid,
            ask=ask,
            reservation=r,
            half_spread=half,
            mid_price=mid_price,
            time=current_time,
        )
        self.quote_history.append(q_obj)
        self._last_quote = q_obj

        logger.debug(
            "t=%.4f  s=%.4f  q=%d  r=%.4f  bid=%.4f  ask=%.4f  spread=%.4f",
            current_time, mid_price, q, r, bid, ask, total_spread,
        )
        return q_obj

    # ------------------------------------------------------------------
    # Fill handlers — called by the engine when a market order hits
    # ------------------------------------------------------------------

    def on_buy_fill(self, mid_price: float, current_time: float) -> InventorySnapshot:
        """
        Process a *buy* fill: a market sell order hit our bid.

        The agent acquires one share at the quoted bid price:
            dX_t  = -p^b   (cash decreases)
            dq_t  = +1     (inventory increases)

        Parameters
        ----------
        mid_price : float
            Mid-price at the time of fill (used for MtM / risk update).
        current_time : float
            Simulation time of the fill.

        Returns
        -------
        InventorySnapshot
            Updated inventory state.

        Raises
        ------
        RuntimeError
            If no quote has been generated yet, or the bid is suppressed.
        """
        if self._last_quote is None:
            raise RuntimeError(
                "on_buy_fill() called before quote() — generate a quote first."
            )
        bid_price = self._last_quote.bid
        if bid_price != bid_price:  # NaN check
            raise RuntimeError(
                "Buy side is suppressed (hard long limit reached); fill ignored."
            )

        delta_cash = -bid_price          # agent pays bid_price for the share
        snap = self.inventory.update(
            delta_q=+1,
            delta_cash=delta_cash,
            mid_price=mid_price,
            current_time=current_time,
        )
        self._buy_fills += 1
        self.fill_history.append(FillRecord(
            time=current_time,
            side="BUY",
            price=bid_price,
            quantity=1,
            cash_delta=delta_cash,
            inventory_after=snap.quantity,
        ))
        logger.debug(
            "BUY FILL  t=%.4f  p^b=%.4f  q=%d  cash=%.4f",
            current_time, bid_price, snap.quantity, snap.cash,
        )
        return snap

    def on_sell_fill(self, mid_price: float, current_time: float) -> InventorySnapshot:
        """
        Process a *sell* fill: a market buy order lifted our ask.

        The agent sells one share at the quoted ask price:
            dX_t  = +p^a   (cash increases)
            dq_t  = -1     (inventory decreases)

        Parameters
        ----------
        mid_price : float
            Mid-price at the time of fill.
        current_time : float
            Simulation time of the fill.

        Returns
        -------
        InventorySnapshot
            Updated inventory state.

        Raises
        ------
        RuntimeError
            If no quote has been generated yet, or the ask is suppressed.
        """
        if self._last_quote is None:
            raise RuntimeError(
                "on_sell_fill() called before quote() — generate a quote first."
            )
        ask_price = self._last_quote.ask
        if ask_price != ask_price:  # NaN check
            raise RuntimeError(
                "Sell side is suppressed (hard short limit reached); fill ignored."
            )

        delta_cash = +ask_price          # agent receives ask_price for the share
        snap = self.inventory.update(
            delta_q=-1,
            delta_cash=delta_cash,
            mid_price=mid_price,
            current_time=current_time,
        )
        self._sell_fills += 1
        self.fill_history.append(FillRecord(
            time=current_time,
            side="SELL",
            price=ask_price,
            quantity=1,
            cash_delta=delta_cash,
            inventory_after=snap.quantity,
        ))
        logger.debug(
            "SELL FILL t=%.4f  p^a=%.4f  q=%d  cash=%.4f",
            current_time, ask_price, snap.quantity, snap.cash,
        )
        return snap

    # ------------------------------------------------------------------
    # State / diagnostics
    # ------------------------------------------------------------------

    def state(self, mid_price: float, current_time: float) -> AgentState:
        """
        Return a complete snapshot of the agent's observable state.

        Parameters
        ----------
        mid_price : float
        current_time : float

        Returns
        -------
        AgentState
        """
        inv = self.inventory
        return AgentState(
            time=current_time,
            mid_price=mid_price,
            quantity=inv.quantity,
            cash=round(inv.cash, 6),
            mark_to_market=round(inv.mark_to_market(mid_price), 6),
                reservation_price=round(
                self.reservation.compute(
                    S=mid_price,
                    q=inv.quantity,
                    t=current_time
                ).price,
                6
            ),
            risk_exposure=round(inv.compute_risk(mid_price, current_time), 6),
            last_quote=self._last_quote,
            limit_breached=inv.check_limits(warn=False),
            total_fills=self._buy_fills + self._sell_fills,
            buy_fills=self._buy_fills,
            sell_fills=self._sell_fills,
            skew_direction=inv.skew_direction(),
        )

    def pnl(self, mid_price: float) -> float:
        """
        Mark-to-market P&L = cash + q * mid_price.

        Equivalent to the terminal value X_T + q_T * S_T from the paper
        (the quantity the agent maximises in expectation).

        Parameters
        ----------
        mid_price : float
            Current (or terminal) mid-price for valuation.

        Returns
        -------
        float
            Current mark-to-market profit/loss in dollars.
        """
        return self.inventory.mark_to_market(mid_price)

    def reset(
        self,
        initial_quantity: int = 0,
        initial_cash: float = 0.0,
    ) -> None:
        """
        Reset the agent to its initial state for a new simulation run.

        Clears all fill / quote history and resets the inventory.

        Parameters
        ----------
        initial_quantity : int
        initial_cash : float
        """
        self.inventory.reset(
            initial_quantity=initial_quantity,
            initial_cash=initial_cash,
        )
        self.quote_history.clear()
        self.fill_history.clear()
        self._last_quote = None
        self._buy_fills = 0
        self._sell_fills = 0
        logger.info(
            "Agent reset: q0=%d  cash0=%.4f", initial_quantity, initial_cash
        )

    # ------------------------------------------------------------------
    # Dunder helpers
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        return (
            f"MarketMakerAgent("
            f"model={self.model}, gamma={self.gamma}, sigma={self.sigma}, "
            f"T={self.T}, k={self.k}, A={self.A}, omega={self.omega}, "
            f"q={self.inventory.quantity}, cash={self.inventory.cash:.4f})"
        )